#ifndef CCHAT_VERSION_TPL_H
#define CCHAT_VERSION_TPL_H

#define CCHAT_VERSION_MAJOR @CCHAT_VERSION_MAJOR@
#define CCHAT_VERSION_MINOR @CCHAT_VERSION_MINOR@

#define CCHAT_COMPILER "@CMAKE_C_COMPILER_ID@"
#define CCHAT_COMPILER_VERSION "@CMAKE_C_COMPILER_VERSION@"

#define MAX_USER_LEN @MAX_USER_LEN@
#define MAX_CHAT_USERS @MAX_CHAT_USERS@

#endif //CCHAT_VERSION_TPL_H
